reviews:
  profile: "assertive"
  auto_review:
    enabled: true
  auto_title_instructions: true
  path_filters:
    - "!**/node_modules/**"
    - "!**/.next/**"
    - "!**/out/**"
    - "!**/public/**"