import React from "react";

export const typo3Constants = [
    { ctype: "bullets", path: "typo3/bullets", component: React.lazy(() => import("../typo3/bullets")) },
    { ctype: "cheader", path: "typo3/cheader", component: React.lazy(() => import("../typo3/cheader")) },
    { ctype: "div", path: "typo3/div", component: React.lazy(() => import("../typo3/div")) },
    { ctype: "form_formframework", path: "typo3/form_formframework", component: React.lazy(() => import("../typo3/form_formframework")) },
    { ctype: "frame", path: "typo3/frame", component: React.lazy(() => import("../typo3/frame")) },
    { ctype: "header", path: "typo3/header", component: React.lazy(() => import("../typo3/header")) },
    { ctype: "html", path: "typo3/html", component: React.lazy(() => import("../typo3/html")) },
    { ctype: "image", path: "typo3/image", component: React.lazy(() => import("../typo3/image")) },
    { ctype: "menu_abstract", path: "typo3/menu_abstract", component: React.lazy(() => import("../typo3/menu_abstract")) },
    { ctype: "menu_categorized_content", path: "typo3/menu_categorized_content", component: React.lazy(() => import("../typo3/menu_categorized_content")) },
    { ctype: "menu_categorized_pages", path: "typo3/menu_categorized_pages", component: React.lazy(() => import("../typo3/menu_categorized_pages")) },
    { ctype: "menu_pages", path: "typo3/menu_pages", component: React.lazy(() => import("../typo3/menu_pages")) },
    { ctype: "menu_recently_updated", path: "typo3/menu_recently_updated", component: React.lazy(() => import("../typo3/menu_recently_updated")) },
    { ctype: "menu_related_pages", path: "typo3/menu_related_pages", component: React.lazy(() => import("../typo3/menu_related_pages")) },
    { ctype: "menu_section", path: "typo3/menu_section", component: React.lazy(() => import("../typo3/menu_section")) },
    { ctype: "menu_section_pages", path: "typo3/menu_section_pages", component: React.lazy(() => import("../typo3/menu_section_pages")) },
    { ctype: "menu_sitemap", path: "typo3/menu_sitemap", component: React.lazy(() => import("../typo3/menu_sitemap")) },
    { ctype: "menu_sitemap_pages", path: "typo3/menu_sitemap_pages", component: React.lazy(() => import("../typo3/menu_sitemap_pages")) },
    { ctype: "menu_subpages", path: "typo3/menu_subpages", component: React.lazy(() => import("../typo3/menu_subpages")) },
    { ctype: "news_categorylist", path: "typo3/news_categorylist", component: React.lazy(() => import("../typo3/news_categorylist")) },
    { ctype: "news_newsdatemenu", path: "typo3/news_newsdatemenu", component: React.lazy(() => import("../typo3/news_newsdatemenu")) },
    { ctype: "news_newsdetail", path: "typo3/news_newsdetail", component: React.lazy(() => import("../typo3/news_newsdetail")) },
    { ctype: "news_newsliststicky", path: "typo3/news_newsliststicky", component: React.lazy(() => import("../typo3/news_newsliststicky")) },
    { ctype: "news_newssearchform", path: "typo3/news_newssearchform", component: React.lazy(() => import("../typo3/news_newssearchform")) },
    { ctype: "news_newssearchresult", path: "typo3/news_newssearchresult", component: React.lazy(() => import("../typo3/news_newssearchresult")) },
    { ctype: "news_newsselectedlist", path: "typo3/news_newsselectedlist", component: React.lazy(() => import("../typo3/news_newsselectedlist")) },
    { ctype: "news_pi1", path: "typo3/news_pi1", component: React.lazy(() => import("../typo3/news_pi1")) },
    { ctype: "news_taglist", path: "typo3/news_taglist", component: React.lazy(() => import("../typo3/news_taglist")) },
    { ctype: "table", path: "typo3/table", component: React.lazy(() => import("../typo3/table")) },
    { ctype: "text", path: "typo3/text", component: React.lazy(() => import("../typo3/text")) },
    { ctype: "textmedia", path: "typo3/textmedia", component: React.lazy(() => import("../typo3/textmedia")) },
    { ctype: "textpic", path: "typo3/textpic", component: React.lazy(() => import("../typo3/textpic")) },
    { ctype: "uploads", path: "typo3/uploads", component: React.lazy(() => import("../typo3/uploads")) }
];
